language: c
os: linux
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - make
    - unrar-free
    - autoconf
    - automake
    - libtool
    - gperf
    - flex
    - bison
    - texinfo
    - gawk
    - ncurses-dev
    - libexpat-dev
    - python-dev
    - python
    - python-serial
    - sed
    - git
    - unzip
    - bash
    - help2man
    - wget
    - bzip2

install:
  - git clone --recursive https://github.com/pfalcon/esp-open-sdk.git ~/esp-open-sdk
  - cd ~/esp-open-sdk && (make STANDALONE=y || cat ~/esp-open-sdk/lx106-hal/config.log)
