language: c
os: linux
dist: trusty

addons:
  apt:
    packages:
    - autoconf
    - build-essential
    - gperf
    - bison
    - flex
    - texinfo
    - libtool
    - libncurses5-dev
    - wget
    - gawk
    - libexpat-dev

cache:
  directories:
  - ~/Espressif

install:
  - "$TRAVIS_BUILD_DIR/.travis/setup-build-environment.sh"

env:
- XTENSA_TOOLS_ROOT=~/Espressif/crosstool-NG/builds/xtensa-lx106-elf/bin SDK_BASE=~/Espressif/ESP8266_SDK ESPTOOL=~/Espressif/esptool/esptool.py

script: make -C "$TRAVIS_BUILD_DIR"
