language: c
os: linux
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - git
    - autoconf
    - build-essential
    - gperf
    - bison
    - flex
    - texinfo
    - libtool
    - libncurses5-dev
    - wget
    - gawk
    - libc6-dev-amd64
    - python-serial
    - libexpat-dev

install:
  - mkdir ~/Espressif
  - git clone -b lx106 git://github.com/jcmvbkbc/crosstool-NG.git ~/Espressif/crosstool-NG
  - cd ~/Espressif/crosstool-NG
  - ./bootstrap && ./configure --prefix=`pwd` && make && make install
