language: c
os: linux
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - make
    - unrar-free
    - autoconf
    - automake
    - libtool
    - gcc-5
    - g++-5
    - gperf
    - flex
    - bison
    - texinfo
    - gawk
    - ncurses-dev
    - libexpat-dev
    - python-dev
    - python
    - python-serial
    - sed
    - git
    - unzip
    - bash
    - help2man
    - wget
    - bzip2

install:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - git clone --recursive https://github.com/pfalcon/esp-open-sdk.git ~/esp-open-sdk
  - cd ~/esp-open-sdk && (make STANDALONE=y || cat ~/esp-open-sdk/lx106-hal/config.log)
